#!/usr/bin/env bash

# Build the app with xcodebuild and package it into a PKG via create_pkg.sh.
# Usage:
#   ./packaging/build_and_pkg.sh            # uses defaults
#   DERIVED_DATA=custom/DD ./packaging/build_and_pkg.sh
#   PKG_NAME=Custom.pkg ./packaging/build_and_pkg.sh
#   VERSION=1.32 ./packaging/build_and_pkg.sh
#   ARCHS="arm64 x86_64" ./packaging/build_and_pkg.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT="${PROJECT:-"$ROOT/Dictant.xcodeproj"}"
SCHEME="${SCHEME:-Dictant}"
DERIVED_DATA="${DERIVED_DATA:-"$ROOT/build/DerivedData"}"
PKG_NAME="${PKG_NAME:-DictantInstaller.pkg}"
IDENTIFIER="${IDENTIFIER:-ilin.pt.Dictant}"
DESTINATION="${DESTINATION:-generic/platform=macOS}"
ARCHS="${ARCHS:-arm64 x86_64}"
ONLY_ACTIVE_ARCH="${ONLY_ACTIVE_ARCH:-NO}"
VERSION_STATE_PATH="$ROOT/packaging/version-state.env"

ARCHIVE_PATH="$ROOT/build/Dictant.xcarchive"
APP_PATH="$ARCHIVE_PATH/Products/Applications/Dictant.app"

build_settings=$(xcodebuild -project "$PROJECT" -scheme "$SCHEME" -showBuildSettings 2>/dev/null || true)
current_build=$(echo "$build_settings" | awk '/CURRENT_PROJECT_VERSION/ {print $3; exit}')
current_marketing=$(echo "$build_settings" | awk '/MARKETING_VERSION/ {print $3; exit}')

marketing_version="${VERSION:-$current_marketing}"

if [[ -z "$marketing_version" ]]; then
  echo "Unable to determine MARKETING_VERSION." >&2
  exit 1
fi

if [[ -n "${CURRENT_PROJECT_VERSION:-}" ]]; then
  next_build="$CURRENT_PROJECT_VERSION"
else
  stored_hash=""
  stored_build=0

  if [[ -f "$VERSION_STATE_PATH" ]]; then
    # This file is generated by this script and contains only a SHA-256 hash
    # and an integer build number.
    source "$VERSION_STATE_PATH"
    stored_hash="${SOURCE_HASH:-}"
    stored_build="${BUILD_NUMBER:-0}"
  fi

  if [[ ! "$stored_build" =~ ^[0-9]+$ ]]; then
    echo "Invalid BUILD_NUMBER in $VERSION_STATE_PATH" >&2
    exit 1
  fi

  source_hash=$(
    git -C "$ROOT" ls-files -co --exclude-standard |
      grep -v '^packaging/version-state\.env$' |
      sort |
      while IFS= read -r file; do
        shasum -a 256 "$ROOT/$file"
      done |
      shasum -a 256 |
      awk '{print $1}'
  )

  if [[ "$source_hash" == "$stored_hash" && "$stored_build" -gt 0 ]]; then
    next_build="$stored_build"
  else
    base_build="$stored_build"
    if [[ "$current_build" =~ ^[0-9]+$ && "$current_build" -gt "$base_build" ]]; then
      base_build="$current_build"
    fi
    next_build=$((base_build + 1))
  fi
fi

echo "Building Dictant $marketing_version ($next_build)..."

echo "Archiving Release app..."
xcodebuild \
  -project "$PROJECT" \
  -scheme "$SCHEME" \
  -configuration Release \
  -archivePath "$ARCHIVE_PATH" \
  -destination "$DESTINATION" \
  ARCHS="$ARCHS" \
  ONLY_ACTIVE_ARCH="$ONLY_ACTIVE_ARCH" \
  MARKETING_VERSION="$marketing_version" \
  CURRENT_PROJECT_VERSION="$next_build" \
  archive

echo "Packaging PKG..."
"$ROOT/packaging/create_pkg.sh" "$APP_PATH" "$PKG_NAME" "$IDENTIFIER" "$marketing_version"

if [[ -z "${CURRENT_PROJECT_VERSION:-}" ]]; then
  printf 'SOURCE_HASH=%s\nBUILD_NUMBER=%s\n' "$source_hash" "$next_build" > "$VERSION_STATE_PATH"
fi
